server:
  port: 8080
  session-timeout: 30
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/legend
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: \!QAZxsw2